org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
#org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.10.7-hotspot
org.gradle.parallel=false
android.useAndroidX=true
android.enableJetifier=true
kotlin.compiler.execution.strategy=in-process

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
